### ISSUE TITLE
rainbow-stack-walk causes Firefox to allocate 24GB of ram

### ISSUE THREAD

**Issue by cpitclaudel** [mattbierner/mattbierner.github.io#1]
Want to open a bug report?

```
$ firefox --version
Mozilla Firefox 47.0
```

**Comment by mattbierner** [comment]
Good idea. I believe this issue is already being tracked, and was first reported back in 2009: https://bugzilla.mozilla.org/show_bug.cgi?id=523950

No browser handles these gifs well. In my super informal testing, Edge has similar memory growth, as do Chrome and Safari (with Safari seeming to be the best of the bunch). I only have a machine with 8GB memory to test on, but these gifs seem to cause most browsers to happily consume all available memory.
