### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TonyJen** [mattbierner/mattbierner.github.io#11]
Hey, saw your site and I can't believe the diversity of your projects and thoughts. I have a question on how do you go about learning and experimenting? 

For example, do you use spiral learning method to understand things or use a unique technique to absorb new information?

Thanks.

**Comment by mattbierner** [comment]
Thanks.

My driving force is to create things and that directs how I go about these personal projects. I don't have much in the way of an official process, but the typical project cycle goes something like:

1. Start with any idea or question that is most interesting to me right now, for example: converting audio propaganda to waveforms.

   I usually try to align this project with some longer term personal goal. One of my current longer term goals for example is to start a business. To do that, I want to become better at selling things. Therefore, my current medium term project is to try selling letterpress prints of the waveforms from propaganda.

1. Research the idea, start learning required skills, and begin prototyping.

    Often—as in the letterpress project—I go in with no idea what I am doing. I always try to keep my specific goal in mind and make sure  I am delivering something, either as learning or as actual prototypes. I'm also trying to become better at collaborating with other people on this and outsourcing the work here (which is itself another longer term goal)

   This stage usually spawns a number of new ideas that I add to a personal backlog. If one of these is more interesting than what I am currently working on, I change the project's focus or abandon it altogether.

1. Polish, release, and share 

1. If the project is still interesting, continue iterating. Otherwise, go back to step 1 and repeat

I try to keep this cycle short but that isn't always practical, so I compensate by having multiple project going on at the same time. These roughly fall into a few different timescales: one-off (a few hours in one go), short (1 or 2 weeks freetime), medium (a month or so with interruptions), and long (3 months+ of very off-and-on work).

This process has let me create, explore, and learn quite a bit without getting burned out. It has also taken me in directions I never expected.

I don't know any of this would work more broadly. Again, my driving force is to just to create things. I'm operating in a bit of a vacuum with no real audience in mind or much in the way of external pressures.

Hope that helps! Let me know if you have any questions

**Comment by TonyJen** [comment]
Very cool, thank you.
