### ISSUE TITLE
Example of how auto doc completion **should** work in VSC?

### ISSUE THREAD

**Issue by dtgriscom** [mattbierner/mattbierner.github.io#9]
Hi, and sorry to bother you. You were kind enough to respond to my Stack Overflow question on [auto jsdoc completion being apparently broken](http://stackoverflow.com/questions/42704909/auto-jsdoc-generation-in-visual-studio-code-broken), asking me to submit a GitHub issue (not here, but at the VSCode repository). I said I'd do so, but haven't yet, because this failure seems so durable under so many circumstances that it almost **has** to be pilot error (either that or nobody has ever tested your code).

Would you please describe a situation where the jscode documentation  **should** be reliably generated? You know: "click the cursor right before any JS or Typescript function, type `/**`, and press `RETURN`, and then bingo: the JSDoc fields will be entered based on the function's argument list and return value"? I'm just guessing I'm doing it wrong, but there's no doc on what "doing it right" would be.

Thanks for your time. And BTW: I greatly enjoyed opening an issue against you.

**Comment by mattbierner** [comment]
No problem, but in the future please open VSCode issues in the VSCode repo and copy my work github account ( @mjbvz ) if you to get my attention. This site is for my decidedly not worked related blog and personal projects.

JSDoc completion should currently work when all of the following are true:

1. You are in a JS or TS file.
2. You have snippet based suggestions enabled in VSCode (since the JSDoc suggestion is a snippet completion item). This is controlled by the `editor.snippetSuggestions` setting. Any value except `none` should work
3. You trigger the JSDoc completion before a function or method. Some valid contexts would be, letting `|` be the cursor:
    ```js
    |
    function abc(x, y, z) { ... } 
    ```

    ```js
    |
    const abc = function(x, y, z) { ... }
    ```

    ```js
    class Foo {
        |
        abc(x, y, z) { ... }
    }
    ```

   These completions should also work if the cursor is after the start of a comment, like so:

    ```js
    /**|
    function abc(x, y, z) { ... } 
    ```

    ```js
    /**| */
    function abc(x, y, z) { ... } 
    ```

We're tracking a few other cases where JSDoc generation should occur but doesn't currently, such as for function expressions. If you notice this feature not working as expected, please [open an issue](https://github.com/Microsoft/vscode/issues/new) over on the VSCode repo and I can take a look.
